import assert from "node:assert/strict";
import { readFileSync, statSync } from "node:fs";
import { createRequire } from "node:module";
const root = new URL("../../", import.meta.url);
const require = createRequire(new URL("package.json", root));
const ts = require("typescript");
const read = path => readFileSync(new URL(path, root), "utf8");
const source = ts.transpileModule(read("apps/web/src/lib/chat-scroll.ts"), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const { createChatScroll } = await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
let scheduled;
const calls = [], listeners = new Map();
globalThis.requestAnimationFrame = fn => { scheduled = fn; return 1; };
globalThis.cancelAnimationFrame = () => { scheduled = undefined; };
globalThis.window = { matchMedia: () => ({ matches: false }) };
const viewport = { scrollTop: 0, scrollHeight: 2000, clientHeight: 600,
  addEventListener(event, fn) { listeners.set(event, fn); }, removeEventListener(event) { listeners.delete(event); } };
const target = name => ({ isConnected: true, scrollIntoView(options) { calls.push({ name, ...options }); } });
const controller = createChatScroll(viewport);
const blocks = ["question1", "question2", "question3", "question4", "result", "input", "user", "assistant", "contact"];
for (const name of blocks) {
  const count = calls.length;
  controller.schedule(target(name), true, name === "input" ? "center" : "start");
  assert.equal(calls.length, count, "wait for post-render animation frame");
  scheduled();
  assert.deepEqual(calls.at(-1), { name, behavior: "smooth", block: name === "input" ? "center" : "start" });
}
listeners.get("wheel")();
controller.schedule(target("incoming-answer"), false); scheduled();
assert.equal(calls.length, blocks.length, "do not interrupt manual history reading");
controller.schedule(target("explicit-question"), true); scheduled();
assert.equal(calls.at(-1).name, "explicit-question");
controller.schedule(target("incoming-answer"), false); scheduled();
assert.equal(calls.at(-1).name, "incoming-answer");
controller.schedule(target("cancelled"), false); listeners.get("touchstart")();
assert.equal(scheduled, undefined, "touch cancels pending focus");
controller.schedule(null, true); scheduled();
const count = calls.length;
controller.schedule({ ...target("unmounted"), isConnected: false }, true); scheduled(); assert.equal(calls.length, count);
controller.dispose(); assert.equal(listeners.size, 0); assert.equal(scheduled, undefined);
const widget = read("apps/web/src/components/chat-widget.tsx");
const css = read("apps/web/src/index.css");
assert.ok(widget.includes('data-testid="chat-bottom-anchor"'));
assert.ok(widget.includes('min-h-0 min-w-0 flex-1 overflow-y-auto'));
assert.ok(widget.indexOf('{renderContactSection()}') > widget.indexOf('aria-label="Диалог"'));
assert.ok(widget.indexOf('{renderContactSection()}') < widget.indexOf('ref={bottomRef}'));
for (const ref of ["currentQuestionRef", "diagnosticResultRef", "postDiagnosticInputRef", "latestAssistantMessageRef", "contactFormRef"]) assert.ok(widget.includes(`ref={${ref}}`) || widget.includes(`? ${ref}`));
assert.ok(css.includes("scroll-margin-top"));
assert.ok(!source.includes("ResizeObserver"));
assert.ok(!widget.includes('<ScrollArea'));
const home = read("apps/web/src/pages/home.tsx");
assert.ok(!home.includes('h-[600px]'));
assert.ok(home.includes('role="dialog"'));
assert.ok(home.includes('aria-modal="true"'));
assert.ok(home.includes('consultation-modal__close'));
assert.ok(home.includes('Персональная рекомендация'));
assert.ok(home.includes('Артём'));
assert.ok(home.includes('src="/artem-consultant.png"'));
assert.ok(css.includes('width: min(1080px, calc(100vw - 32px))'));
assert.ok(css.includes('height: min(840px, calc(var(--chat-viewport-height, 100dvh) - 32px))'));
assert.ok(css.includes('grid-template-columns: minmax(0, 1fr) 316px'));
assert.ok(css.includes('@media (max-width: 899px)'));
assert.ok(css.includes('@media (max-width: 639px)'));
assert.ok(css.includes('height: var(--chat-viewport-height, 100dvh)'));
assert.ok(css.includes('overflow-wrap: anywhere'));
assert.ok(home.includes('window.visualViewport'));
assert.ok(statSync(new URL("apps/web/public/artem-consultant.png", root)).size > 100_000);
const card = widget.slice(widget.indexOf('function ResultCard'), widget.indexOf('// ─── Main component'));
assert.ok(!/overflow-hidden|line-clamp|max-h-/.test(card), "long card remains unbounded inside viewport");
for (const [width, height] of [[375,667],[390,844],[430,932],[768,1024],[820,1180],[1366,768],[1440,900],[1920,1080]]) {
  const margin = width < 640 ? 0 : 32;
  const modalHeight = width < 640 ? height : Math.min(840, height - margin);
  const modalWidth = width < 640 ? width : Math.min(1080, width - margin);
  assert.ok(modalHeight > 0 && modalHeight + margin <= height);
  assert.ok(modalWidth + margin <= width);
}
console.log("PASS: semantic chat focus, modal composition, Artem portrait, and responsive desktop/tablet/mobile constraints across 8 viewports (not browser rendering).");
