import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
const root = new URL("../../", import.meta.url);
const require = createRequire(new URL("package.json", root));
const ts = require("typescript");
const read = path => readFileSync(new URL(path, root), "utf8");
const source = ts.transpileModule(read("apps/web/src/lib/chat-scroll.ts"), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const { createChatScroll } = await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
let scheduled;
const calls = [], listeners = new Map();
globalThis.requestAnimationFrame = fn => { scheduled = fn; return 1; };
globalThis.cancelAnimationFrame = () => { scheduled = undefined; };
globalThis.window = { matchMedia: () => ({ matches: false }) };
const viewport = { scrollTop: 0, scrollHeight: 2000, clientHeight: 600,
  addEventListener(event, fn) { listeners.set(event, fn); }, removeEventListener(event) { listeners.delete(event); } };
const target = name => ({ isConnected: true, scrollIntoView(options) { calls.push({ name, ...options }); } });
const controller = createChatScroll(viewport);
const blocks = ["question1", "question2", "question3", "question4", "result", "input", "user", "assistant", "contact"];
for (const name of blocks) {
  const count = calls.length;
  controller.schedule(target(name), true, name === "input" ? "center" : "start");
  assert.equal(calls.length, count, "wait for post-render animation frame");
  scheduled();
  assert.deepEqual(calls.at(-1), { name, behavior: "smooth", block: name === "input" ? "center" : "start" });
}
listeners.get("wheel")();
controller.schedule(target("incoming-answer"), false); scheduled();
assert.equal(calls.length, blocks.length, "do not interrupt manual history reading");
controller.schedule(target("explicit-question"), true); scheduled();
assert.equal(calls.at(-1).name, "explicit-question");
controller.schedule(target("incoming-answer"), false); scheduled();
assert.equal(calls.at(-1).name, "incoming-answer");
controller.schedule(target("cancelled"), false); listeners.get("touchstart")();
assert.equal(scheduled, undefined, "touch cancels pending focus");
controller.schedule(null, true); scheduled();
const count = calls.length;
controller.schedule({ ...target("unmounted"), isConnected: false }, true); scheduled(); assert.equal(calls.length, count);
controller.dispose(); assert.equal(listeners.size, 0); assert.equal(scheduled, undefined);
const widget = read("apps/web/src/components/chat-widget.tsx");
const css = read("apps/web/src/index.css");
assert.ok(widget.includes('data-testid="chat-bottom-anchor"'));
assert.ok(widget.includes('min-h-0 min-w-0 flex-1 overflow-y-auto'));
assert.ok(widget.indexOf('{renderContactSection()}') > widget.indexOf('aria-label="Диалог"'));
assert.ok(widget.indexOf('{renderContactSection()}') < widget.indexOf('ref={bottomRef}'));
for (const ref of ["currentQuestionRef", "diagnosticResultRef", "postDiagnosticInputRef", "latestAssistantMessageRef", "contactFormRef"]) assert.ok(widget.includes(`ref={${ref}}`) || widget.includes(`? ${ref}`));
assert.ok(css.includes("scroll-margin-top"));
assert.ok(!source.includes("ResizeObserver"));
assert.ok(!widget.includes('<ScrollArea'));
assert.ok(!read("apps/web/src/pages/home.tsx").includes('h-[600px]'));
assert.ok(css.includes('height: 82dvh'));
assert.ok(css.includes('max-width: 560px'));
assert.ok(css.includes('max-height: calc(var(--chat-viewport-height, 100dvh)'));
assert.ok(css.includes('overflow-wrap: anywhere'));
assert.ok(read("apps/web/src/pages/home.tsx").includes('window.visualViewport'));
const card = widget.slice(widget.indexOf('function ResultCard'), widget.indexOf('// ─── Main component'));
assert.ok(!/overflow-hidden|line-clamp|max-h-/.test(card), "long card remains unbounded inside viewport");
for (const [width, height] of [[375,667],[390,844],[430,932],[768,1024],[820,1180],[1366,768],[1440,900],[1920,1080]]) {
  const margin = width < 640 ? 8 : 32;
  const chatHeight = width >= 1024 ? Math.min(height * .82, height - margin) : height - margin;
  const chatWidth = width >= 1024 ? Math.min(560, width - margin) : width - margin;
  assert.ok(chatHeight > 0 && chatHeight + margin <= height);
  assert.ok(chatWidth + margin <= width);
}
console.log("PASS: semantic block targets/post-render scheduling/manual override/cleanup; responsive CSS and 8 viewport constraint cases (not browser rendering).");
