import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
const root = new URL("../../", import.meta.url);
const require = createRequire(new URL("package.json", root));
const ts = require("typescript");
const read = path => readFileSync(new URL(path, root), "utf8");
const source = ts.transpileModule(read("apps/web/src/lib/chat-scroll.ts"), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const { createChatScroll } = await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
let scheduled, resized, disposed = false, calls = 0;
globalThis.requestAnimationFrame = fn => { scheduled = fn; return 1; };
globalThis.cancelAnimationFrame = () => { scheduled = undefined; };
globalThis.window = { matchMedia: () => ({ matches: false }) };
globalThis.ResizeObserver = class { constructor(fn) { resized = fn; } observe() {} disconnect() { disposed = true; } };
let onScroll;
const viewport = { scrollTop: 600, scrollHeight: 1000, clientHeight: 400,
  addEventListener(event, fn) { assert.equal(event, "scroll"); onScroll = fn; }, removeEventListener() {} };
const bottom = { parentElement: {}, scrollIntoView(options) { assert.equal(options.block, "end"); calls++; } };
const controller = createChatScroll(viewport, bottom);
controller.schedule(); assert.equal(calls, 0, "wait for layout frame"); scheduled(); assert.equal(calls, 1);
viewport.scrollHeight = 1400; resized(); scheduled(); assert.equal(calls, 2, "follow newly rendered long result");
viewport.scrollTop = 200; onScroll(); controller.schedule(); scheduled(); assert.equal(calls, 2, "respect reading above bottom");
controller.schedule(true); scheduled(); assert.equal(calls, 3, "explicit action resumes following");
viewport.scrollTop = 1000; onScroll(); controller.schedule(); scheduled(); assert.equal(calls, 4);
controller.dispose(); assert.ok(disposed); assert.equal(scheduled, undefined);
const widget = read("apps/web/src/components/chat-widget.tsx");
const css = read("apps/web/src/index.css");
assert.ok(widget.includes('data-testid="chat-bottom-anchor"'));
assert.ok(widget.includes('min-h-0 min-w-0 flex-1 overflow-y-auto'));
assert.ok(widget.indexOf('{renderContactSection()}') > widget.indexOf('aria-label="Диалог"'));
assert.ok(widget.indexOf('{renderContactSection()}') < widget.indexOf('ref={bottomRef}'));
assert.ok(!widget.includes('<ScrollArea'));
assert.ok(!read("apps/web/src/pages/home.tsx").includes('h-[600px]'));
assert.ok(css.includes('height: 82dvh'));
assert.ok(css.includes('max-width: 560px'));
assert.ok(css.includes('max-height: calc(var(--chat-viewport-height, 100dvh)'));
assert.ok(css.includes('overflow-wrap: anywhere'));
assert.ok(read("apps/web/src/pages/home.tsx").includes('window.visualViewport'));
const card = widget.slice(widget.indexOf('function ResultCard'), widget.indexOf('// ─── Main component'));
assert.ok(!/overflow-hidden|line-clamp|max-h-/.test(card), "long card remains unbounded inside viewport");
for (const [width, height] of [[375,667],[390,844],[430,932],[768,1024],[820,1180],[1366,768],[1440,900],[1920,1080]]) {
  const margin = width < 640 ? 8 : 32;
  const chatHeight = width >= 1024 ? Math.min(height * .82, height - margin) : height - margin;
  const chatWidth = width >= 1024 ? Math.min(560, width - margin) : width - margin;
  assert.ok(chatHeight > 0 && chatHeight + margin <= height);
  assert.ok(chatWidth + margin <= width);
}
console.log("PASS: scroll scheduling/follow/manual override/cleanup; responsive CSS and 8 viewport constraint cases (not browser rendering).");
