import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const root = new URL("../../", import.meta.url);
const widget = readFileSync(new URL("apps/web/src/components/chat-widget.tsx", root), "utf8");
const home = readFileSync(new URL("apps/web/src/pages/home.tsx", root), "utf8");
const styles = readFileSync(new URL("apps/web/src/index.css", root), "utf8");

assert.ok(!widget.includes('data-testid="button-start-diagnostic"'));
assert.ok(!widget.includes('aria-label="Начать диагностику"'));
assert.ok(!widget.includes("Подберём программу<br />под ваш опыт и цели"));
assert.match(widget, /if \(step === 0 && !sessionError && sessionId && !schemaLoading && diagnosticSchema\.length === 4\) handleStart\(\)/);
assert.match(widget, /const handleStart = \(\) => \{\s*if \(!sessionId \|\| diagnosticSchema\.length !== 4 \|\| initializationStarted\.current\) return;/);
assert.match(widget, /createSession\.mutate\(undefined,[\s\S]*onSuccess: \(data\) => setSessionId\(data\.sessionId\)/);
assert.match(widget, /<ProgressBar current=\{1\} total=\{4\} \/>/);
assert.match(widget, /sessionError \? <div className="diagnostic-recommendation__error" role="alert">[\s\S]*onClick=\{retryInitialization\}/);
assert.ok(widget.includes("Подготавливаем диагностику..."));
assert.ok(!widget.includes("Здравствуйте."));
assert.ok(!widget.includes('data-testid="button-begin-questions"'));
assert.ok(!widget.includes("handleBeginQuestions"));
assert.ok(home.includes('src="/artem-expertovich.jpg"'));
assert.ok(home.includes("Артём Экспертович"));
assert.ok(home.includes("Персональный консультант ИНОБР"));
assert.ok(home.includes("Знания сегодня."));
assert.ok(home.includes('onClick={closeConsultation}'));
assert.ok(!home.includes("<span>Закрыть</span>"));
assert.equal((home.match(/className="consultation-modal__close"/g) ?? []).length, 1);
assert.ok(widget.includes('<div className="diagnostic-launch__logo"><img src={INOBR_LOGO_SRC}'));
assert.ok(widget.includes('<ArrowUpRight aria-hidden="true" />'));
assert.ok(existsSync(new URL("apps/web/public/artem-expertovich.jpg", root)));
assert.match(styles, /\.consultation-modal--launch,[\s\S]*?\.consultation-modal--diagnostic,[\s\S]*?\.consultation-modal--recommendation,[\s\S]*?\.consultation-modal--consultation\s*\{[\s\S]*?width:\s*min\(1150px,[\s\S]*?height:\s*min\(600px/);
assert.match(styles, /\.diagnostic-launch-person__card img\s*\{[\s\S]*?height:\s*286px/);
assert.ok(widget.includes("<ProgressBar current={displayedQIndex + 1} total={4} />"));
assert.ok(widget.includes("{displayedQuestion.questionText}"));
assert.ok(widget.includes("const dictItems = q.options"));
assert.ok(widget.includes('aria-pressed={selectedCode === opt.code}'));
assert.ok(widget.includes("handleDiagnosticBack(displayedQIndex)"));
assert.ok(widget.includes("handleDiagnosticNext(displayedQIndex)"));
assert.ok(widget.includes("pendingAnswer.code !== \"other\" || customInput.trim()"));
assert.match(styles, /\.diagnostic-question__options > button\.is-selected\s*\{[^}]*background:\s*#f2b631/);
assert.match(styles, /\.diagnostic-question__options > button\s*\{[^}]*align-items:\s*center[^}]*justify-content:\s*center[^}]*text-align:\s*center/);
assert.ok(!styles.includes(".consultation-modal--launch .consultation-modal__close"));
assert.ok(home.includes('!diagnosticCompleted ? " consultation-modal--diagnostic"'));
assert.ok(!home.includes("diagnosticStarted"));
assert.ok(!home.includes("consultation-modal--launch"));
assert.ok(home.includes('" consultation-modal--recommendation"'));
assert.ok(home.includes("!diagnosticCompleted || recommendationActive"));

console.log("PASS: immediate Q1 initialization, controlled retry, question layout/photo and close wiring.");
