import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const root = new URL("../../", import.meta.url);
const widget = readFileSync(new URL("apps/web/src/components/chat-widget.tsx", root), "utf8");
const helper = readFileSync(new URL("apps/web/src/lib/manager-form.ts", root), "utf8");
const css = readFileSync(new URL("apps/web/src/index.css", root), "utf8");
const route = readFileSync(new URL("apps/api/src/routes/manager-form.ts", root), "utf8");

assert.match(widget, /role="dialog"[\s\S]*aria-modal="true"/);
assert.match(widget, /iframe[\s\S]*managerWidgetUrl\(conversationId\)/);
assert.match(widget, /event\.source !== managerWidgetRef\.current\?\.contentWindow/);
assert.match(widget, /getcourse-manager-widget/); assert.match(widget, /status === "success"/);
assert.match(helper, /manager-form\/widget/); assert.match(helper, /sourceUrl:\s*window\.location\.href/);
assert.doesNotMatch(widget, /contactEmail|contactPhone|personalDataConsent|marketingConsent/);
assert.match(widget, /setContactPhase\(null\)[\s\S]*window\.location\.href\s*=\s*"https:\/\/inobr-expert\.ru"/);
assert.match(widget, /event\.key === "Escape"[\s\S]*closeManagerForm/);
assert.match(widget, /event\.target === event\.currentTarget[\s\S]*closeManagerForm/);
assert.doesNotMatch(widget, /CONTACT_CHANNELS|submitContact/);
assert.match(widget, /setContactPhase\("submitted"\)/);
assert.match(helper, /referrer:\s*document\.referrer/);
assert.match(route, /submitGetCourseWidgetBody[\s\S]*recordEvent\(sessionId, "manager_form_submit"\)/);
assert.match(css, /\.manager-form-overlay[\s\S]*overflow-y:\s*auto/);
assert.match(css, /@media \(max-width:\s*640px\)[\s\S]*\.manager-form-modal/);
console.log("PASS G-L: modal fields/context, X/Escape/backdrop exit redirect, error retention, success-only event and responsive layout wiring.");
